### ISSUE TITLE
/uploads gitignore에 추가 제안

### ISSUE THREAD

**Issue by SeungjaeLee00** [SeungjaeLee00/Instagram_Clone#13]
/uploads 에 올라가는 정보는 회원 개인 정보니깐 gitignore에 추가하는 것이 좋을 것 같음

**Comment by zIswim** [comment]
-> AWS S3버킷에 올리는 걸로 코드 수정
-> uploads 폴더는 삭제하고 .env 파일만 .gitignore에 추가!!
